apiVersion: v1
kind: Service
metadata:
  name: cackalacky-badge-api-service
  namespace: cackalacky
  labels:
    app: cackalacky-badge-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: cackalacky-badge-api