apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cackalacky-badgeapi-argocd
  namespace: argocd
spec:
  destination:
    namespace: cackalacky
    server: "https://kubernetes.default.svc"
  source:
    path: manifests
    repoURL: "https://<github_username>:<personal access token>@github.com/lockfale/cackalacky-badge-api"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncOptions:
        - PruneLast=true
  revisionHistoryLimit: 1